site_name: LakeOps
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt

repo_url: https://github.com/hoaihuongbk/lakeops

nav:
  - Getting Started: index.md
  - User Guide:
      - Working With Delta Lake: guide/working_with_delta_lake.md
      - Working With Iceberg: guide/working_with_iceberg.md
      - Working With Google Sheets: guide/working_with_google_sheets.md
      - Working With Secrets: guide/working_with_secrets.md
  - Engines: guide/engines.md
  - API Reference:
      - ops.read: apis/ops.read.md
      - ops.write: apis/ops.write.md
      - ops.execute: apis/ops.execute.md
      - secrets.read: apis/secrets.read.md
      - secrets.write: apis/secrets.write.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
