site_name: LakeOps
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Getting Started: index.md
  - User Guide:
      - Basic Usage: guide/basic-usage.md
      - Engines: guide/engines.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
