site_name: LakeOps
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt

repo_url: https://github.com/hoaihuongbk/lakeops

nav:
  - Getting Started: index.md
  - Engines: guide/engines.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
