name: Deploy Docs

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build docs
        run: uv run mkdocs build --clean

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
