name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  docs:
    needs: [setup]
    uses: ./.github/workflows/common.yml
    steps:
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build docs
        run: mkdocs build --clean
      - name: Deploy docs
        run: mkdocs gh-deploy --force
