name: Publish to PyPI

on:
  release:
    types: [ created ]

jobs:
  pypi-publish:
    needs: [ setup ]
    uses: ./.github/workflows/common.yml
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Install dependencies
        run: |
          uv sync

      - name: Build package
        run: uv build --wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
